# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-11-04T14:58:41+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import AnyUrl, BaseModel


class Software(BaseModel):
    name: str
    """
    The name of the software.
    """
    version: str
    """
    The version of the software.
    """
    repository: AnyUrl
    """
    The URL of the software's source code repository.
    """
    homepage: AnyUrl
    """
    The URL to the software's homepage.
    """
    logo: Optional[AnyUrl] = None
    """
    A URL to an image of the software logo.
    """


class Api(BaseModel):
    name: str
    """
    The name of the software API.
    """
    version: str
    """
    The version of the API implemented by the software.
    """
    base_url: Optional[AnyUrl] = None
    """
    The absolute URL to the API base.
    """
    rel_url: str
    """
    A relative URL to the API base.
    """
    documentation: str
    """
    A relative or absolute URL to the API documentation.
    """


class ServiceInfo(BaseModel):
    version: str
    """
    The version of the service info specification.
    """
    software: Software
    api: Dict[str, Api]
